# NOTE: The underlying Twilio SDKs require a minimum deployment target of 8.1
platform :ios, '8.1'

# Fix "Generated duplicate UUIDs"
install! 'cocoapods', :deterministic_uuids => false

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/twilio/cocoapod-specs'

target 'ReactNativeTwilioIPMessagingExample' do

  # Linked libraries
  pod 'React', :path => '../node_modules/react-native'
  pod 'RCTTwilioChat', :path => '../node_modules/react-native-twilio-ip-messaging/ios'
  
  # Install Libraries
  pod 'TwilioChatClient', '~> 0.16.0'
  pod 'TwilioAccessManager', '~> 0.1.1'

end
